version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_cmVmaW5lZC1kaW5vc2F1ci01OS5jbGVyay5hY2NvdW50cy5kZXYk
      - CLERK_SECRET_KEY=sk_test_ycQHAwlxi7n2vxYdL8FYwbiCl7UOyY76nJErFuS3MW
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://valky:6379
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=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

    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    depends_on:
      - valky
      - qdrant

  valky:
    image: valkey/valkey
    ports: 
      - "6379:6379"
    volumes:
      - valky_data:/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  valky_data:
  qdrant_data: